### ISSUE TITLE
Compile Failure on OSX

### ISSUE THREAD

**Issue by jac32** [murarth/linefeed#1]
Hey, this doesn't seem to build on OSX on rust 1.10.0 stable.

Here's a gist with the output of cargo build --verbose: 
https://gist.github.com/jac32/b6c78e6a0f92be7a00fbf04a4e0c9727

**Comment by murarth** [comment]
I've just pushed a fix for this. Would you care to test and let me know if there are any other issues?

**Comment by jac32** [comment]
Yeah I can do that 👍

**Comment by waywardmonkeys** [comment]
Master works on OS X. Version 0.1.1 gave me the same problem as was reported here.

**Comment by murarth** [comment]
@waywardmonkeys: Thanks. I've published master to crates.io as version 0.1.2.
