### ISSUE TITLE
Wrong behaviour after entering unicode string

### ISSUE THREAD

**Issue by gwenn** [murarth/linefeed#15]
a) Launch the demo
b) Input `a̐éö̲`
c) Move to the left at least four times
the cursor is now in the middle of the prompt.

**Comment by murarth** [comment]
It looks like your example string has some combined characters. (Is that what they're called?) I'm very much not familiar with the more subtle aspects of Unicode, so I will learn more about this and then come up with a fix. Thanks for the issue!
