### ISSUE TITLE
No `ncursesw` on macOS.

### ISSUE THREAD

**Issue by waywardmonkeys** [murarth/linefeed#2]
On macOS, I don't seem to have either a `libtinfo` or a `libncursesw`. What is the correct build approach here?

**Comment by murarth** [comment]
I'm not sure how these things work on Mac. `brew install curses` or something equivalent with MacPorts? Depending on which you prefer, I guess?

**Comment by waywardmonkeys** [comment]
It looks like on macOS, you can just link against `ncurses` instead of `ncursesw` ... I created a symlink: `ln -s /usr/lib/libncurses.dylib /usr/local/lib/libncursesw.dylib` and then my test application was able to link and run.

**Comment by murarth** [comment]
That's odd, but it does seem that you're correct. The ncurses project FAQ (http://invisible-island.net/ncurses/ncurses.faq.html#what_platforms) indicates that `ncursesw` is not supported on Mac OS, while `ncurses` is supported.

`linefeed` is only using the `terminfo` functions, anyway, so it shouldn't matter. I'll push a change for this right away.
