### ISSUE TITLE
Terminal seems count length of escape sequences chars

### ISSUE THREAD

**Issue by mitnk** [murarth/linefeed#20]
When using some color sections in one line, like in this image:
<img width="1110" alt="wx20171221-141654 2x" src="https://user-images.githubusercontent.com/177049/34243152-71044cd2-e65a-11e7-97be-2b2c32bc6b48.png">

Terminal wraps the line into the beginning of same line.

is this an issue of linefeed?

OS: Mac
Terminal: iTerm2

PS. input long strings seems ok:
<img width="1436" alt="wx20171221-143022 2x" src="https://user-images.githubusercontent.com/177049/34243395-8258a02c-e65b-11e7-8772-8eee27630bbc.png">

**Comment by murarth** [comment]
Are you using characters `\x01` and `\x02` to indicate escape sequences, as outlined in the [`set_prompt` docs](https://docs.rs/linefeed/0.3.0/linefeed/reader/struct.Reader.html#method.set_prompt)?

**Comment by mitnk** [comment]
yes. [like this](https://github.com/mitnk/cicada/blob/master/src/libs/colored.rs#L8).

**Comment by murarth** [comment]
Okay, I found the problem. The invisible sequence indicators were being discarded too soon and the prompt rendering function was assuming that all characters were visible.

I've just pushed a commit that fixes this. If everything seems to be working, you can close this issue.

**Comment by mitnk** [comment]
Thanks @murarth, it works!
