### ISSUE TITLE
specify a position for prompt

### ISSUE THREAD

**Issue by Tacklebox** [murarth/linefeed#24]
Hi, let me start by saying thanks. I think this project is super cool and really well done!

I am not sure if this falls into the intended use case of linefeed as its not really a 'line' but since this has one of the best editing experiences I have seen I figured I would ask.

Would it be possible to specify an X,Y position and maximum size on the terminal to draw the prompt line?

The use case would be for embedding linefeed into a tui/rustbox/termion ui as a small user input box.

**Comment by murarth** [comment]
It should be possible to implement the [`Terminal` trait](https://docs.rs/linefeed/0.4.0/linefeed/terminal/trait.Terminal.html) using one of those as a backend. Then, create a `Reader` using [`Reader::with_term`](https://docs.rs/linefeed/0.4.0/linefeed/reader/struct.Reader.html#method.with_term). As long as the `Terminal` trait is implemented correctly, `Reader` should behave as expected.

**Comment by Tacklebox** [comment]
Thanks for the quick response. I will take a look at that route.
