### ISSUE TITLE
How to Pass Extra Info to Completers

### ISSUE THREAD

**Issue by mitnk** [murarth/linefeed#25]
When creating a Reader, I want to attach some extra info (an object maybe) with it, so that later in completers, I can use it to provide info for TAB completion.

```
pub struct BinCompleter;

impl<Term: Terminal> Completer<Term> for BinCompleter {
    fn complete(
        &self,
        word: &str,
        _reader: &Reader<Term>,
        _start: usize,
        _end: usize,
    ) -> Option<Vec<Completion>> {
        Some(complete_bin(...))
    }
}
```

For example, in `fn complete_bin()` above, I want to iterate all aliases preset for the executable binaries completion. Is there a way to pass this info along to the Completion implementation? Thanks in advance!

**Comment by murarth** [comment]
Sharing data with completers would be done the same way you usually share ownership in Rust -- using `Rc` or `Arc`; and using `RefCell` or `Mutex`/`RwLock` if you need to mutate the shared data.

**Comment by mitnk** [comment]
Maybe there is a big gap on my knowledge of Rust, I still don't get what I should do.

So I put code of using linefeed's completion here. Could you point me out where the `Rc` can step in and take action (I want to access the `sh` instance inside the impl of `BinCompleter::complete()`)?

The follow code are copied and modified a bit from `examples/path_completion.rs`:

```rust
extern crate linefeed;
use std::rc::Rc;
use linefeed::{Reader, ReadResult};

use somemod::Shell;
use somemod::BinCompleter;

fn main() {
    let sh = Shell::new();

    let mut reader = Reader::new("path-completion-demo").unwrap();
    reader.set_completer(Rc::new(BinCompleter));
    reader.set_prompt("path> ");

    while let Ok(ReadResult::Input(line)) = reader.read_line() {
        println!("read input: {:?}", line);

        if !line.trim().is_empty() {
            reader.add_history(line);
        }
    }

    println!("Goodbye.");
}
```

**Comment by murarth** [comment]
Something like this:

```rust
struct BinCompleter {
    // BinCompleter contains a shared reference to a living Shell.
    // With this, it can look up alias names, etc.
    sh: Rc<Shell>,
}

fn main() {
    // Make the Shell instance shared
    let sh = Rc::new(Shell::new());

    // ...

    reader.set_completer(Rc::new(
        // Share the Shell instance with the completer
        BinCompleter{sh: sh.clone()}));
}
```

**Comment by mitnk** [comment]
Indeed a big gap out there.. Thanks a ton @murarth for your time on the Rust training.
