### ISSUE TITLE
No way to get a reader.term from outside

### ISSUE THREAD

**Issue by survived** [murarth/linefeed#33]
Hi! Thanks for the project, it has a much more useful API then others similar libs have. I can adjust almost anything to my purpose, although I can't use a term which is captured by `Reader`. Can we make it public?

The use case would be for defining [Function](https://docs.rs/linefeed/0.4.0/linefeed/reader/struct.Reader.html#method.define_function) printing some text after the prompt and refreshing an input line. It may be the function which is printing hints for the argument under cursor. Now there's only one way to implement this logic — through LogSender, but it prints line before the prompt and avoids a terminal escapes. I want to make function which would works just like [completer](https://docs.rs/linefeed/0.4.0/src/linefeed/reader.rs.html#1322-1352) it would seems prettier.

Following changes are resolving the problem:
- Implement `term_mut` and (for symmetry) `term`:
```rust
impl<Term: Terminal> Reader<Term> {
    // ...
    /// Returns a mutable reference to `Term`.
    pub fn term_mut(&mut self) -> &mut Term { &mut self.term }
    /// Returns a immutable reference to `Term`.
    pub fn term(&self) -> &Term { &self.term }
    // ...
}
```
- Make method `draw_prompt` of `Reader` public (or create similar method called `refresh_line`):
```rust
impl<Term: Terminal> Reader<Term> {
    // ...
    pub fn draw_prompt(&mut self) -> io::Result<()> { /* ... */ }
    // ...
}
```

Or maybe there's some purpose why the Term's hidden?

**Comment by murarth** [comment]
The `Term` instance is private to prevent interfering with the operations of `Reader`. If one were to use `Term` directly for either reading or writing, it is very likely you would get incorrect results.

A public accessor could be implemented, with the documented caveat that certain methods will interfere with `Reader`, but for now, I think it will suffice to add public methods to erase the prompt, print text, and restore the prompt.

I've just pushed a commit that adds these methods. Please, take a look and tell me whether it solves your use case.

**Comment by survived** [comment]
It completely solves my use case. Although it escapes unprintable characters, it isn't critical. I guess the support of unprintable characters is difficult task.

Thanks so much!

**Comment by murarth** [comment]
@survived: If you want unprintable characters written out as-is, you can use `println!` or `io::stdout` as you normally would. As long as `erase_prompt` and `restore_prompt` are called before and after, the `println!` output won't interfere with linefeed's management of terminal state.

**Comment by survived** [comment]
Thanks! I'll try to print in that way.

**Comment by survived** [comment]
@murarth, did linefeed v0.5.0 lose possibility to print text throughout executing of `Function`?

**Comment by murarth** [comment]
@survived: The API was removed, but I don't believe there's any reason it can't be added again. I'll take a look shortly (and add an example using this functionality to make sure the API won't be accidentally removed again).

**Comment by murarth** [comment]
@survived: I've added an accessor to the new `Writer` API, through the method `Prompter::writer`. Much more convenient than the old erase-write-restore thing.

**Comment by survived** [comment]
It's actually prettier than it was. Thank you!

**Comment by murarth** [comment]
I know, right? I didn't realize the usefulness of `Drop`-able guard types until I had to use `MutexGuard`s all over the place. Very useful for managing temporary data states, like an erased prompt.

**Comment by survived** [comment]
Yea, `Drop`-able guard types make printing and other things easier and prettier and safer, but erase-write-restore things were more flexible, they made me able to avoid erasing of prompt, so I could write `Function` similar to autocomplete (it doesn't erase the prompt too).

**Comment by survived** [comment]
@murarth, Is it possible to make `Writer` that keeps old prompt on its place and restore a new one when drops?

**Comment by survived** [comment]
Well, thing like `println!(); writeln!(prompter.writer()?, "{}", some_stuff)?;` solves my use case, and I suppose it doesn't spoil `linefeed` logic (at least on the last version of the crate), but it's kind of bad solution.)

**Comment by murarth** [comment]
@survived: I've just pushed a commit that adds a new method (and renames the old `lock_writer`/`writer` methods, for clarity) to allow writing text after the prompt, then redrawing.

**Comment by survived** [comment]
Thank you!
