### ISSUE TITLE
Move to winapi 0.3

### ISSUE THREAD

**Issue by Lokathor** [murarth/linefeed#34]
The `winapi` crate has been on 0.3 for a while, which offers much better compile times for most code bases since you can pick to compile and bind against just the win32 modules you'll be using.

**Comment by murarth** [comment]
There's a pretty big not-a-rewrite-but-a-lot-of-stuff-will-change thing I'll be releasing (hopefully) pretty soon. It will include updating to `winapi` 3.0.

You can leave this issue open until I get that released.

**Comment by murarth** [comment]
The aforementioned rewrite is done. The `winapi` dependency is now version 0.3.

**Comment by Lokathor** [comment]
Any ETA on when we might see a "linefeed 0.5" on crates.io?

**Comment by murarth** [comment]
Very soon. I want to take a little time to see if any bugs shake out of the recent changes, but I probably won't be waiting too long.

**Comment by mitnk** [comment]
Haven't tested more, but notice the original `Reader::set_history_size()` and `history_size()` are missing.
