### ISSUE TITLE
Outputs Mess into Inputs Lines When Cursor is in First Line of Inputs

### ISSUE THREAD

**Issue by mitnk** [murarth/linefeed#35]
```
$ echo III when run a very very long command which 
wraps into multiple lines
```
And `Enter` Key hit when cursor at the `III` position, then the output `when run a ...` will show up the same line of `wraps into ...` line. The correct way should output at the line below the `wraps into ..` line.

**Comment by murarth** [comment]
Wow. This is such an obvious bug. I'm surprised it wasn't caught sooner.

Just pushed the fix. Thanks for the issue.
