### ISSUE TITLE
ability to specify initial value for read_line buffer

### ISSUE THREAD

**Issue by neilvandyke** [murarth/linefeed#39]
It would be useful for some purposes, if an initial buffer value for `read_line` could be specified.

I didn't see a way in the documentation to do this.  In the code, it looks like `read_line_impl` proceeds from a `reset_input`, to `draw_prompt`, to an input loop that only processes signals before `try_read_char`.  I didn't see a non-kludge way to that the initial buffer value could be set without modifying the code of the `linefeed` crate.  (I'm relatively new to Rust, so please pardon me if I'm making a mistake.)

The partial workaround I'm using in my application program is to put the desired initial value in the history before calling `line_feed`.  But it would be nice to have this value be in the buffer immediately, without the user needing to know that it is available in the history, and retrieve it from the history.

(BTW, thank you for your work on the `linefeed` crate.  I like it.)

**Comment by murarth** [comment]
I think this could be done, if `read_line` were modified to reset input after the input loop (once the user has pressed Enter or EOF). I'm working on a big rewrite at the moment. Once I'm finished with that, I'll see what I can do about this issue.

**Comment by murarth** [comment]
The aforementioned rewrite is done. And I've added a new API on top to modify prompt data.
