### ISSUE TITLE
Please add an option to add an item to the history only if it's different from the most recent history

### ISSUE THREAD

**Issue by Lokathor** [murarth/linefeed#40]
There doesn't appear to be an obvious way to do this simply. The best indirect route seems to be something like

```rust
if reader.history_len() > 0 && reader.history().nth(reader.history_len() - 1) != Some(input.as_ref()) {
  reader.add_history(input.clone());
} else if reader.history_len() == 0 {
  reader.add_history(input.clone());
}
```

but it would be handy if there was something more direct. Could call it `add_history_unless_duplicate`

**Comment by murarth** [comment]
Sounds like a good idea. I've just pushed a commit to add this.

Thanks for the issue.
