### ISSUE TITLE
Change newline bug

### ISSUE THREAD

**Issue by driftluo** [murarth/linefeed#43]
When the command is too long, more than one line limit will not be automatically change newline, there is a strange format

**Comment by driftluo** [comment]
Oh, I found the problem. I used the `ansi_term` library to dye the prompt `xx>` . When the command line too long, there was a bug. If I didn't dye it, there wouldn't be a problem. Is there any other action I need to do here?

**Comment by murarth** [comment]
`linefeed` code is unable to determine which characters will be visible and which are part of an escape sequences (like those generated by `ansi_term` to encode colors).

As described in the [`set_prompt` documentation](https://docs.rs/linefeed/0.5.0/linefeed/interface/struct.Interface.html#method.set_prompt), you must insert the character `\x01` immediately before any escape sequences and insert `\x02` immediately after the escape sequence.

**Comment by driftluo** [comment]
When I set it like follow, there is no problem with the one-line command, but when multi-line, `ctrl+a` + `ctrl+k` returns the wrong position, causing the prompt to also delete.
```
interface.set_prompt(format!("\x01{}\x02", Red.bold().paint("cita >")).as_str());
```
[![0eb988e530a11df3f025e28e3e8c6098.md.gif](https://static.wodetu.cn/images/2018/06/01/0eb988e530a11df3f025e28e3e8c6098.gif)

**Comment by murarth** [comment]
Only the invisible portions of the string should be surrounded by `\x01` and `\x02`. This indicates to `linefeed` which characters should be ignored when calculating the visual width of the prompt string.

Using `ansi_term`, that would look something like this:

```rust
let style = Red.bold();
let text = "cita >";

interface.set_prompt(&format!("\x01{prefix}\x02{text}\x01{suffix}\x02",
    prefix=style.prefix(),
    text=text,
    suffix=style.suffix()));
```

**Comment by driftluo** [comment]
Great! Thank you very much for your patience. My knowledge of the terminal is still too weak.
