### ISSUE TITLE
Access to the input when Signal happened.

### ISSUE THREAD

**Issue by crlf0710** [murarth/linefeed#45]
Hello, i'm writing a program with a REPL interface. So i give `linefeed` a test and it looks nice!

However I've met with a problem: I want to simulate the Node.js style Ctrl-C handling: only erase current input if the input's not empty, prompt for first key-press and exit for the second when input is not.

Currently `linefeed` can give Ctrl-C as an `Interrupt` Signal, without any indication on whether user has input something.

**Comment by crlf0710** [comment]
I've added this function to `Reader` as a workaround. I'm not sure if this is appropriate though...
```
    /// Check if the input buffer is not empty.
    pub fn is_buffer_empty(&mut self) -> bool {
        if self.lock.read_line_running {
            self.prompter().buffer().is_empty()
        } else {
            true
        }
    }
```

**Comment by crlf0710** [comment]
Besides this, i've found that when `read_line` returns `Signal`, the cursor is still on the input line. But i can't append text there, since `writeln!` to `Interface` will erase the existing text. I don't think this is expected behavior in any case.  Currently i decide to just `writeln!("{}{}^C", prompt, buffer());` as a workaround.

**Comment by murarth** [comment]
@crlf0710: Yes, the behavior of `linefeed` upon receiving a reported signal value is currently incorrect. It should do the same thing it does when returning a successful result.

The correct behavior is to clear the current input buffer and reset the `read_line` state, in preparation for the next `read_line` call. This would prevent application code from viewing the state of the input buffer prior to receipt of the `Interrupt` signal.

The reset is performed at the end of a `read_line` call in order to permit modification of the initial state before `read_line` begins (a feature which was requested by #39).

**Comment by murarth** [comment]
Actually, on second thought, returning a reported signal does not need to terminate the `read_line` call. It only needs to be properly documented that the `read_line` call may be resumed or ended by the user after a `ReadResult::Signal(_)` is returned.

I've pushed a commit that adds this documentation and another that adds a public `buffer` method to `Interface`, which should allow you to implement the desired functionality.

**Comment by crlf0710** [comment]
OK, cool~ I'll give it a try.

**Comment by crlf0710** [comment]
Yes it works fine.  I didn't realize `cancel_read_line()` could be so useful here!

One more question. I want to simulate the effect of `echo_control_characters` when Ctrl-C happens, currently i called this new `buffer()` method, append `"^C"` to it and `setbuffer()` to put it on the screen before i call `cancel_read_line()`.  It seems the current effect is what i want. Is this the proper way to do so?

**Comment by murarth** [comment]
@crlf0710: Yes, that would be the way to do it right now.

I could also make the `Prompter` available from the `Reader`. It would allow applications to mess around with the `read_line` state outside of a `Command` implementation, but that would be opening a can of worms that could lead to some unforeseen bugs.

**Comment by crlf0710** [comment]
Great, thanks.
Actually i think if `prompter` is implementation details, the whole prompter mod should not be exported...

Anyway, I'm gonna close this.
