### ISSUE TITLE
Interface won't instantiate

### ISSUE THREAD

**Issue by jjpe** [murarth/linefeed#48]
I have a binary, the main fn of which roughly looks like this:

````
fn main() -> ReplResult<()> {
    // code omitted for brevity

    println!("before");
    let interface = Interface::new("sxi-repl").map_err(ReplErr::from)?;
    println!("after");

    // more code omitted
    Ok(())
}
````

The text `before` gets printed, but `after` does not. 
Instead, I see this error:  `Error: EvalErr(IoErr { kind: Other, description: "failed to parse terminfo entry" })
`.
Taking away the error wrapping, the I/O error is left over, and that tells me that somehow instantiating the `Interface` type fails.

I'm using `Fedora 28`, and `rustc 1.28.0 (9634041f0 2018-07-30)`.

**Comment by jjpe** [comment]
It looks like it's happening due to an incompatible value for the `$TERM` env var.
Changing the value from `xterm-color` to `xterm-256color` makes the issue go away.

Still,  I have to ask: could such support be added to `linefeed`?

**Comment by murarth** [comment]
I've just published an updated version of a dependent crate. If you run `cargo update` in your project's directory, it should bring in the latest version of the [`terminfo`](https://github.com/meh/rust-terminfo) crate, which was recently updated to accept more terminfo database formats.

I believe this should solve your issue.

**Comment by jjpe** [comment]
I believe it has, thanks!
