### ISSUE TITLE
Strange history-search-backward Behavior

### ISSUE THREAD

**Issue by mitnk** [murarth/linefeed#51]
With inputrc set with:
```
$ cat ~/.inputrc
"\e[A": history-search-backward
"\e[B": history-search-forward
```
We run:
```
$ cargo run --example demo
demo> echo 234
read input: "echo 234"
demo> echo <UP>
demo> echo III234 
# III means cursor position
# now, I want to immediately update the command to "echo 1234",
# thus I type "1". However, the following shows up:
(failed i-search)`echo 1': echo 234

# If I type Enter now, I got:
demo> echo 234
read input: "echo 234"
```
Checked the counterpart in Bash, no such surprising (user-interrupting) behavior.

I expect that the `history-search-backward` prompt shouldn't be shown when an "immediately char typing" after a `<UP>` history search (i.e. should be the same behavior in Bash).

**Comment by mitnk** [comment]
Like you may manage guessed - this issue was introduced after the commit `fbcbcc52751` (behavior on `fbcbcc52751` is correct) :-)

**Comment by murarth** [comment]
Oof. I forgot that the `history-search-forward`/`backward` commands (which I never use) are completely different from the `forward`/`reverse-search-history` commands (which I use all the time). Inconsistent command naming is my least favorite part of GNU Readline compatibility.

I've just pushed a fix for this. Thanks for the issue.
