### ISSUE TITLE
Stuck when canceling path completion prompt

### ISSUE THREAD

**Issue by mitnk** [murarth/linefeed#53]
Hi, me again :)

Based on the setup environment from https://github.com/murarth/linefeed/issues/50

```
$ cargo run --example path_completion
path> ./tmp/f-<TAB><TAB>
Display all 1000 possibilities? (y/n)  # Let's Ctrl-C here
```

After hitting `Ctrl-C` on the `y/n` prompt, linefeed stuck and do not receive new inputs.

**Comment by murarth** [comment]
Just pushed a commit that fixes this. Thanks for the issue.
