### ISSUE TITLE
Multiple-line support?

### ISSUE THREAD

**Issue by mitnk** [murarth/linefeed#55]
I don't see anywhere in linefeed that if multiple-line input is supported. Does linefeed support it, or is it easy to add this ability? Thanks!

```
bash $ echo foo\
> bar
foobar
```

**Comment by murarth** [comment]
No, multi-line input is not inherently supported by `linefeed`. However, there are two ways of implementing it using currently available APIs. Each method produces subtle differences in the interface.

1. By replacing the command bound to newline (`'\n'`), as seen in `examples/enter_function.rs`. The custom command either calls `prompter.accept_input()`, which is equivalent to the default behavior, or insert a newline character into the buffer.  
Implementing multi-line input this way means that the user may freely move the cursor backward, to the first line. However, it is not (currently) possible to draw a second prompt, as in your example.
2. Alternatively, one may implement multi-line input, without replacing the newline-bound command, by setting a new prompt and making another `.read_line()` call. This does allow the rendering of a secondary prompt, but does not allow editing previous lines, as `linefeed` does not retain previous inputs.

Multi-line input is not built into `linefeed`, as there is no clear reason to favor either of these methods. However, if there's any API that can be added to better facilitate either or both of these uses (without excluding the use of the other), I'm open to adding such an API.

**Comment by mitnk** [comment]
Thanks a lot for your inputs!

Bash (v4.x) is using the second method - it won't allow user to edit the previous lines.

I'm closing this issue for now. I'm ok with current situation, just a wonder.
