### ISSUE TITLE
Make mortal optional

### ISSUE THREAD

**Issue by segeljakt** [murarth/linefeed#67]
I'd like to try use linefeed for the web with the [xterm.js](https://github.com/xtermjs/xterm.js/) terminal emulator. Would it be possible to make mortal an optional feature? Currently, mortal has dependencies which prevent linefeed from being compiled to WASM.

**Comment by murarth** [comment]
Making the mortal dependency optional would not be my preference. linefeed uses a number of utility types defined in mortal. Moving these types into linefeed would mean a not insignificant amount of code duplication between the two projects.

However, it might be possible to implement a web backend for mortal. This would allow linefeed to work on the web platform without any modification. If you're interested in submitting a PR to mortal to implement the web backend, I'll do my best to help with any issues you encounter in the process.

**Comment by segeljakt** [comment]
sounds interesting, I will investigate if it's possible 👍

**Comment by murarth** [comment]
Great! I'm going to close this issue and, if any issues arise, please feel free to file an issue on mortal.
