### ISSUE TITLE
support for ctrl-f/b for forward char and back char

### ISSUE THREAD

**Issue by noyez** [murarth/linefeed#9]
Sorry if this isn't the best to way to patch, i'm still learning github.

Simple Patch here: https://gist.github.com/noyez/0f27d0b4732b233f30425b22b81bf3d8

**Comment by murarth** [comment]
The way to make a contribution to a project on GitHub is through the pull request process.

GitHub has a guide on the subject: https://help.github.com/articles/creating-a-pull-request/

The short version is: Make a fork of this project, push your commit to your fork, then submit a pull request for that commit.

**Comment by noyez** [comment]
fixed by pr:#10
